### PR TITLE
Issue/26 material ui demo

### PR DESCRIPTION
**Pull request by vitkon**
#### What's this PR do?
adds a link to a codesandbox demo

#### Where should the reviewer start?
`README.md`

#### How should this be manually tested?
see if demo makes sense

### CODE REVIEW

**Comment by mattdell** [comment]
I really like this. Should we include a warning in the demo?

**Comment by vitkon** [comment]
Once we have they type  exported, we should

**Comment by vitkon** [comment]
we need a release, right?

**Comment by mattdell** [comment]
Ahhh, yes of course because codesandbox.io uses the deployed version.

**Comment by vitkon** [comment]
I'm releasing now while on the train

**Comment by mattdell** [comment]
Sorry, didn't think you'd be so responsive!

**Comment by vitkon** [comment]
I was doing it anyway, not related to your comment.

**Comment by vitkon** [comment]
Demo is updated with a warning now. Enum export didn't quite work, I had to use string.
need to look into it.

**Pull request merged**
